### ISSUE TITLE
Rich text in Angular

### ISSUE THREAD

**Issue by amandasage** [kgajera/ngx-contentful-rich-text#2]
Hey Kishan,

I have a user trying to render rich text in Angular 8

npm install @contentful/rich-text-react-renderer --save
npm install @contentful/rich-text-from-markdown --save
npm install @contentful/ngx-contentful-rich-text --save

let obj = {
nodeType: 'document',
data: {},
content: [
{
nodeType: 'paragraph',
content: [
{
nodeType: 'text',
value: formdata[item],
marks: [],
data: {}
}
],
data: {}
}
]
};

They're returning

ERROR in ./node_modules/@contentful/rich-text-from-markdown/dist/rich-text-from-markdown.es5.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\rupajc1\Pet-Partner-Onboarding-Portal\node_modules\@contentful\rich-text-from-markdown\dist'
ERROR in ./node_modules/@contentful/rich-text-react-renderer/dist/rich-text-react-renderer.es5.js
Module not found: Error: Can't resolve 'react' in 'C:\Users\rupajc1\Pet-Partner-Onboarding-Portal\node_modules\@contentful\rich-text-react-renderer\dist'

Do you know what other information they need to provide to help resolve this?

**Comment by kgajera** [comment]
For an Angular project, you should not be using `@contentful/rich-text-react-renderer`. And you probably don't need `@contentful/rich-text-from-markdown` either.

**Comment by kgajera** [comment]
I'm going to close this issue because the errors are not related to this repository but let me know if you need further help.
