### ISSUE TITLE
Line breaks on paragraphs are ignored

### ISSUE THREAD

**Issue by fbaba-nibtravel** [kgajera/ngx-contentful-rich-text#4]
Hi, I'm having an issue with line breaks within paragraphs. They are being ignored on the default implementation for paragraphs. 

I'm trying to implement a custom one, but looking at your default, I don't quite see a way (yet) to get the `node.content` and replace `\n` as `<br />` and was wondering if you have suggestion. 
Also, this should be a good feature to implement on the library as line breaks are quite useful as paragraphs usually contains a lot more spacing between the lines. 

Edit: 

To give a bit more context, the custom renderer allows the user to set a custom renderer for block types. e.g.: h1, h2, paragraph, ul, etc...
The issue presents when a simple text is added. The default TextValueComponent simply binds the node value to the template. Hence, any HTML present on the string text is rendered as plain string.
https://github.com/kgajera/ngx-contentful-rich-text/blob/a83339447580daede3071f41d88a92fc676b8cc8/projects/ngx-contentful-rich-text/src/lib/components/text-value.component.ts#L5

This means that even if I manage to replace the line carriage feed to a `<br>`, the text component won't render the line breaks properly. Raised a PR to address this issue. Please review it @kgajera

**Comment by kgajera** [comment]
Using the following CSS in your project should create line breaks for `\n`:

```
ngx-contentful-rich-text p {
  white-space: pre-wrap;
}
```

Let me know if that works for you, otherwise I'll take another look at the PR.

**Comment by fbaba-nibtravel** [comment]
@kgajera, thanks! Got caught up with angular + contentful that completely forgot about this css property. That works!
