### ISSUE TITLE
Type-Error

### ISSUE THREAD

**Issue by Kyoss79** [kgajera/ngx-contentful-rich-text#44]
Currently I get the following error when trying to build my project

```error TS2322: Type '(Block | Inline | Text)[] | (Inline | Text)[]' is not assignable to type '(Block | Inline)[]'.
  Type '(Block | Inline | Text)[]' is not assignable to type '(Block | Inline)[]'.

1 <ngx-contentful-rich-text [nodes]="node.content"></ngx-contentful-rich-text>
```

Using
- "@contentful/rich-text-types": "15.11.1"
- "ngx-contentful-rich-text": "^0.6.0"

You have any clue how to solve this?

**Comment by JoseRobertoReyesEncora** [comment]
Having the same issue, it seems the input `nodes` lack the `Text` type, since the `content` property of a `Block` node is defined as `(Block | Inline | Text)[]` in the definition of the `@contentful/rich-text-types` module.

**Comment by JoseRobertoReyesEncora** [comment]
> Currently I get the following error when trying to build my project
> 
> ```
>   Type '(Block | Inline | Text)[]' is not assignable to type '(Block | Inline)[]'.
> 
> 1 <ngx-contentful-rich-text [nodes]="node.content"></ngx-contentful-rich-text>
> ```
> 
> Using
> 
> * "@contentful/rich-text-types": "15.11.1"
> * "ngx-contentful-rich-text": "^0.6.0"
> 
> You have any clue how to solve this?

There's a work around, you could cast the `node.content` as `<Array<Block | Inline>>` on a new property, or method. It seems to work well, but I'm not sure regarding this solution.

**Comment by kgajera** [comment]
Completed by #56
