### ISSUE TITLE
Request: Export services ComponentRendererService and RendererProviderService

### ISSUE THREAD

**Issue by KristinaTsoleva** [kgajera/ngx-contentful-rich-text#45]
At the moment both services ComponentRendererService and RendererProviderService are created using providedIn: "root". In this case services are always provided at the most top level.

We have a problem when using  <ngx-contentful-rich-text></ngx-contentful-rich-text> inside a child module or inside a lib (repo created using nx).

When we provide a component to be rendered with nodeRenderers and the component in depending on a service that is NOT providedIn: 'root', but it is actually provided in the specific module, we get an error that there is no provider for that service, even though there is one in the child module. 

The reason for that is that the ComponentRendererService and the RendererProviderService are providedIn: 'root', so when they call the createComponent method they are searching for the components dependancies in the root provider and not in the actual child module.

The fix for this would be to just import these two services in the child module and that is how we are going to have a way to maintain where they are provide.  That way when they are called they first try to find the providers inside the child module. 

At the moment this is not possible as they are not exported from the lib.

**Comment by kgajera** [comment]
Thanks for reporting this. I just published a new version, `0.8.0`, that exports the `RendererProviderService` and refactors to remove the `ComponentRendererService`. Let me know if you still have any issues.

**Comment by KristinaTsoleva** [comment]
Thank you for the quick update. Now it works as expected.
