### ISSUE TITLE
EMBEDDED_ASSET / Images

### ISSUE THREAD

**Issue by sgrinblat** [kgajera/ngx-contentful-rich-text#48]
Hi how are you? Thank you very much for creating this, it is a great help in dealing with Rich Text problem.

However, I don't quite understand how it works. At the moment I am only using this in the html:

`<ngx-contentful-rich-text
      [document]="blogPost.fields.content">
 </ngx-contentful-rich-text>`

And honestly this pretty much covers what I need, since it's able to recreate the hr, b, heading, etc. But, it fails to recreate an image that has been placed in the body.

How can I do that? If anyone has a repository where they have used this and have been able to use the images, perhaps that is enough for me to understand it.

Thank you all so much for your time!

**Comment by kgajera** [comment]
@sgrinblat Here's an example: https://stackblitz.com/edit/ngx-contentful-rich-text-aasi43?file=src/app/app.component.ts
