### ISSUE TITLE
Update `@contentful/rich-text-types` to version `16`

### ISSUE THREAD

**Issue by Yberion** [kgajera/ngx-contentful-rich-text#54]
Hello,

Would it be possible to update the `@contentful/rich-text-types` to the version `16`?

I don't know enough about the migration process to propose a PR for that.

Have a nice day!

cc @kgajera

**Comment by kgajera** [comment]
Completed by https://github.com/kgajera/ngx-contentful-rich-text/commit/6278511caf6d04ea301a740b734d894ff7a96190 and released in [v0.9.0](https://github.com/kgajera/ngx-contentful-rich-text/releases/tag/v0.9.0)
