### ISSUE TITLE
${CHILDREN} not working

### ISSUE THREAD

**Issue by YusufIpek** [kgajera/ngx-contentful-rich-text#55]
I am placing ${CHILDREN} into a class which extends the NodeRenderer, but the compiler doesn't compile and I am getting the following error: 

Here is my code:

import { Component, OnInit } from '@angular/core';
import { marked } from 'marked';
import { CHILDREN, NodeRenderer } from 'ngx-contentful-rich-text';

@Component({
  styleUrls: ['./paragraph-entry.component.sass'],
  template: '<div>${CHILDREN}</div>',
})
export class ParagraphEntryComponent extends NodeRenderer implements OnInit {
  htmlContent: string;
  ngOnInit(): void {}
}

@Component({
  selector: 'rich-text',
  template: `
    <div class="rich-text-wrapper">
      <ngx-contentful-rich-text
        [document]="document!"
        [nodeRenderers]="nodeRenderers">
      </ngx-contentful-rich-text>
    </div>
  `,
  styleUrls: ['./rich-text.component.sass'],
})
export class RichTextComponent implements OnInit {

  constructor() {}
  document = {...}

  nodeRenderers: Record<string, NodeRendererResolver> = {
    [BLOCKS.PARAGRAPH]: _node => ParagraphEntryComponent
  };

}

Error message:
`
  Type '(Block | Inline | Text)[]' is not assignable to type '(Block | Inline)[]'.
    Type 'Block | Inline | Text' is not assignable to type 'Block | Inline'.
      Type 'Text' is not assignable to type 'Block | Inline'.
        Property 'content' is missing in type 'Text' but required in type 'Inline'.
`

The content of ${CHILDREN} "<ngx-contentful-rich-text [nodes]=\"node.content\"></ngx-contentful-rich-text>" is responsible for the problem, node.content has type (Block|Inline|Text)[] but [nodes] expects (Block|Inline)[]. 
What am I doing wrong here?

**Comment by jacksonopp** [comment]
I am also seeing the same issue.
