### ISSUE TITLE
Build Component based on node data

### ISSUE THREAD

**Issue by MarcoGlauser** [kgajera/ngx-contentful-rich-text#6]
Thank you for this library!

It would be nice if it were possible to define the `NodeRenderer` dynamically based on the node data. This would enable the rendering of embedded entries with different components based on their content type.
This would also make it possible to easily re-use existing Components that work with contentful entries.

something like this would be awesome:
```js
  componentContentTypeMapping = {
    'product': ProductComponent,
    'review': ReviewComponent
  }

  nodeRenderers: Record<string, Type<NodeRenderer> | ((node: Block | Inline | Text) => Type<NodeRenderer>)> = {
    [BLOCKS.EMBEDDED_ENTRY]: (node) => {
      const component = this.componentContentTypeMapping[node.data.target.sys.contentType.sys.id]
      if (component !== undefined) {
        return component
      }
      return DefaultNodeRendererComponent
    },
  };
```

**Comment by kgajera** [comment]
I agree, that's a good idea. I won't get a chance to work on this until next week. If you need it sooner, feel free to submit a PR.
